name       : pcsx2
version    : 1.4.0
release    : 1
source     :
    - https://github.com/PCSX2/pcsx2/archive/v1.4.0.tar.gz : 2c8a986e2b6514d7018f6cfd39c4f2a72229b9b4ab06ca6b1d3466dfd9c33005
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : games.emulator
summary    : PCSX2 - The Playstation 2 Emulator
description: |
    PCSX2 is an open-source PlayStation 2 (AKA PS2) emulator. Its purpose is to emulate the PS2 hardware, using a combination of MIPS CPU Interpreters, Recompilers and a Virtual Machine which manages hardware states and PS2 system memory. This allows you to play PS2 games on your PC, with many additional features and benefits.
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(liblzma)
    - pkgconfig32(libpng)
    - pkgconfig32(gl)
    - pkgconfig32(glew)
    - pkgconfig32(gtk+-2.0)
    - pkgconfig32(portaudio-2.0)
    - pkgconfig32(soundtouch)
    - pkgconfig32(sdl2)
    - pkgconfig32(zlib)
    - pkgconfig32(x11)
    - pkgconfig32(xext)
    - bzip2-32bit-devel
    - glibc-32bit-devel
    - libaio-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
    - ninja
    - png++
    - wxwidgets-32bit-devel
rundeps    :
    - libaio
    - libaio-32bit
patterns   :
    - /usr/lib32
setup      : |
    # Upstream fix for GCC6
    %patch -p1 < $pkgfiles/0001-common-Backport-upstream-GCC6-compilation-issue.patch
    
    mkdir solusBuildDir
    pushd solusBuildDir
    export WXWIDGETSEMUL32=1
    
    # TODO: Sort out the nvidia-cg-toolkit fiasco
    %cmake -G Ninja -DCMAKE_BUILD_TYPE=Release .. \
        -DCMAKE_AR=/usr/bin/gcc-ar \
        -DCMAKE_RANLIB=/usr/bin/gcc-ranlib \
        -DCMAKE_NM=/usr/bin/gcc-nm \
        -DPACKAGE_MODE=TRUE \
        -DCMAKE_TOOLCHAIN_FILE="cmake/linux-compiler-i386-multilib.cmake" \
        -DCMAKE_LIB_SUFFIX="32" \
        -DPLUGIN_DIR="/usr/lib32/%package%" \
        -DGAMEINDEX_DIR='/usr/share/%package%' \
        -DEXTRA_PLUGINS=FALSE \
        -DXDG_STD=TRUE
build      : |
    ninja %JOBS% -C solusBuildDir
install    : |
    DESTDIR="%installroot%" ninja install %JOBS% -C solusBuildDir
